apiVersion: v1
kind: Secret
metadata:
  name: test-secret-basic-auth
  namespace: test-nsp
type: kubernetes.io/basic-auth
stringData:
  username: admin      # required field for kubernetes.io/basic-auth
  password: t0p-Secret # required field for kubernetes.io/basic-auth