apiVersion: v1
kind: Secret
metadata:
  name: test-yaml-secret-dev
  namespace: dev-1
  annotations:
    kapp.k14s.io/create-strategy: fallback-on-update
    kapp.k14s.io/change-group: namespace-provisioner.apps.tanzu.vmware.com/delete-after-app
type: Opaque
stringData:
  content.yaml: |
    xmas-fifth-day:
      calling-birds: four
      french-hens: 3
      golden-rings: 5
      partridges:
        count: 1
        location: "a pear tree"
      turtle-doves: two